name: favorite_places
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  location: ^7.0.1
  http: ^1.2.2
  google_maps_flutter: ^2.10.0
  path_provider: ^2.1.5
  path: ^1.9.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
